repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: Format Markdown with Prettier
        files: \.md$
        exclude: ^(CLAUDE\.md|README\.md)$
        
  - repo: local
    hooks:
      - id: markdown-lint-strict
        name: Strict Markdown Lint
        entry: python lint_markdown_strict.py
        language: python
        files: \.md$
        pass_filenames: false
        args: [docs]
        additional_dependencies: [pyyaml]
        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]