site_name: Studio3 Guides
site_description: Complete documentation for Studio3 - Where Belief Becomes Momentum
site_url: https://inocult.github.io/studio3-docs/
site_author: Studio3 Team
repo_url: https://github.com/inocult/studio3-docs
repo_name: inocult/studio3-docs
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

  font:
    text: Inter
    code: Fira Code

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - glightbox
  - awesome-pages

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.extra
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/studio3
    - icon: fontawesome/brands/discord
      link: https://discord.gg/studio3
    - icon: fontawesome/brands/github
      link: https://github.com/studio3
  
  analytics:
    provider: google
    property: G-XXXXXXXXXX

extra_css:
  - stylesheets/extra.css
  - stylesheets/pdf.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  
  - Quickstart:
    - quickstart/index.md
    - What is Studio3?: quickstart/what-is-studio3.md
    - How It Works: quickstart/how-it-works.md
    - Key Benefits: quickstart/key-benefits.md
    - Get Started: quickstart/get-started.md
  
  - Overview Guide:
    - overview-guide/index.md
    - Introduction:
      - What is Studio3: overview-guide/what-is-studio3.md
      - Ecosystem Overview: overview-guide/ecosystem-overview.md
      - Key Principles: overview-guide/key-principles.md
    - Core Concepts:
      - The Arena System: overview-guide/arena-system.md
      - Belief & Doubt Signals: overview-guide/belief-signals.md
      - Three-NFT System: overview-guide/nft-system.md
    - The Journey:
      - Seven Phase Lifecycle: overview-guide/seven-phases.md
      - Milestone System: overview-guide/milestones.md
      - Progression Rules: overview-guide/progression.md
    - Participants:
      - Three Roles Overview: overview-guide/roles-overview.md
      - How They Interact: overview-guide/interactions.md
      - Aligned Incentives: overview-guide/incentives.md
    - Economics:
      - $SIGNAL Token: overview-guide/signal-token.md
      - Rewards & Penalties: overview-guide/rewards-system.md
      - Value Flow: overview-guide/value-flow.md
    - Getting Started:
      - Choosing Your Role: overview-guide/choosing-role.md
      - First Steps: overview-guide/first-steps.md
      - Resources & Support: overview-guide/resources.md
  
  - Senders Guide:
    - senders-guide/index.md
    - Getting Started:
      - Founder Basics: senders-guide/founder-basics.md
      - Requirements: senders-guide/requirements.md
      - Creating Your Spark: senders-guide/creating-spark.md
    - The Forge:
      - Understanding Duels: senders-guide/forge-duels.md
      - Winning Strategies: senders-guide/winning-strategies.md
      - Duel Preparation: senders-guide/duel-preparation.md
    - Building:
      - Container DAO Setup: senders-guide/container-dao.md
      - Milestone Planning: senders-guide/milestone-planning.md
      - MVP Development: senders-guide/mvp-development.md
    - Community:
      - Engaging Supporters: senders-guide/engaging-echoes.md
      - Handling Doubt: senders-guide/handling-doubt.md
      - Building Momentum: senders-guide/building-momentum.md
    - Growth:
      - Navigating Drift: senders-guide/drift-navigation.md
      - Achieving Orbit: senders-guide/achieving-orbit.md
      - Flare Scaling: senders-guide/flare-scaling.md
    - Exit:
      - Planning Ascension: senders-guide/ascension-planning.md
      - Buyback Process: senders-guide/buyback-process.md
      - Post-Graduation: senders-guide/post-graduation.md
  
  - Echoes Guide:
    - echoes-guide/index.md
    - Fundamentals:
      - Understanding Your Role: echoes-guide/echo-basics.md
      - Signal Mechanics: echoes-guide/signal-mechanics.md
      - Rewards & Risks: echoes-guide/rewards-system.md
    - Getting Started:
      - Your First Signals: echoes-guide/first-signals.md
      - Managing Tokens: echoes-guide/token-management.md
      - Building Reputation: echoes-guide/reputation-building.md
    - Analysis:
      - Evaluating Ventures: echoes-guide/evaluating-ventures.md
      - Reading Signals: echoes-guide/reading-signals.md
      - Due Diligence: echoes-guide/due-diligence.md
    - Strategies:
      - When to Believe: echoes-guide/belief-strategies.md
      - Strategic Doubt: echoes-guide/doubt-strategies.md
      - Portfolio Management: echoes-guide/portfolio-management.md
    - Advanced:
      - Phase Strategies: echoes-guide/phase-strategies.md
      - Contrarian Plays: echoes-guide/contrarian-plays.md
      - Risk Management: echoes-guide/risk-management.md
    - Community:
      - Participation: echoes-guide/community-engagement.md
      - Building Influence: echoes-guide/influence-building.md
      - Echo Networks: echoes-guide/echo-networks.md
  
  - Anchors Guide:
    - anchors-guide/index.md
    - Fundamentals:
      - The Anchor Role: anchors-guide/anchor-role.md
      - Responsibilities: anchors-guide/responsibilities.md
      - Requirements: anchors-guide/requirements.md
    - Validation:
      - Framework: anchors-guide/validation-framework.md
      - Milestone Review: anchors-guide/milestone-review.md
      - Evidence Assessment: anchors-guide/evidence-assessment.md
    - Mentorship:
      - Guiding Founders: anchors-guide/guiding-founders.md
      - Strategic Advice: anchors-guide/strategic-advice.md
      - Crisis Management: anchors-guide/crisis-management.md
    - Standards:
      - Quality Criteria: anchors-guide/quality-criteria.md
      - Red Flags: anchors-guide/red-flags.md
      - Best Practices: anchors-guide/best-practices.md
    - Advanced:
      - Dispute Resolution: anchors-guide/dispute-resolution.md
      - Governance: anchors-guide/ecosystem-governance.md
      - Anchor Council: anchors-guide/anchor-council.md
    - Growth:
      - Progression: anchors-guide/anchor-progression.md
      - Compensation: anchors-guide/compensation.md
      - Reputation: anchors-guide/reputation-management.md
      - Influence Building: anchors-guide/influence-building.md