name: Validate Documentation

on:
  push:
    paths:
      - 'docs/**/*.md'
      - 'mkdocs.yml'
      - 'lint_markdown_strict.py'
      - '.prettierrc'
      - 'package.json'
  pull_request:
    paths:
      - 'docs/**/*.md'
      - 'mkdocs.yml'
      - 'lint_markdown_strict.py'
      - '.prettierrc'
      - 'package.json'

jobs:
  validate:
    name: Validate Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        echo "📦 Installing all dependencies..."
        make install
        
    - name: Check markdown formatting with Prettier
      run: |
        echo "💅 Checking markdown formatting..."
        make format-check
        
    - name: Run MkDocs strict validation
      run: |
        echo "🔍 Running MkDocs strict validation..."
        make build-strict
        
    - name: Run custom markdown linter
      run: |
        echo "🔍 Running strict markdown linter..."
        make lint > lint_output.txt 2>&1 || true
        
        # Show summary but don't fail on warnings
        if grep -q "ERROR:" lint_output.txt; then
          echo "❌ Critical markdown errors found!"
          head -50 lint_output.txt
          exit 1
        else
          echo "✅ No critical errors found"
          echo "Summary:"
          tail -10 lint_output.txt
        fi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: documentation-build
        path: |
          site/
          lint_output.txt